### GET / 
GET http://localhost:5000

### Register a user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "sisyphus@gmail.com",
  "password": "123123123"
}

### Register a user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "username1",
  "password": "123123123"
}

### Login a user POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "sisyphus@gmail.com",
  "password": "123123123"
}

### Login a user with wrong password POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "sisyphus@gmail.com",
  "password": "wrongpass"
}







### Fetch all posts GET /posts (protected)
GET http://localhost:5000/posts/all?pid=-1&sort=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc1MDg1MDc4LCJleHAiOjE3NzUxNzE0Nzh9.i9E07S5oMeD6hTwzSS0VPzkNK2AQC283pqFdBAZhHD8

### Creates a new post POST /posts (protected)
POST http://localhost:5000/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc1MDgzNzYxLCJleHAiOjE3NzUxNzAxNjF9.gYIQBfmLqqiwqpq-TtiqmRXh3ph5ZKB7e6pnmhNMYPs
Content-Type: application/json

{
  "title": "title",
  "content": "this is the post content",
  "username": "sisyphus@gmail.com",
  "parent": null,
  "tagString": "Intro"
}

### Update a post PUT /posts/:id (protected)
PUT http://localhost:5000/posts/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc1MDg1MDc4LCJleHAiOjE3NzUxNzE0Nzh9.i9E07S5oMeD6hTwzSS0VPzkNK2AQC283pqFdBAZhHD8

{
  "title": "new title",
  "content": "new content",
  "tagString": "Discussion"
}


### Delete a post DELETE /posts/:id (protected)
DELETE http://localhost:5000/posts/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc1MDg1MDc4LCJleHAiOjE3NzUxNzE0Nzh9.i9E07S5oMeD6hTwzSS0VPzkNK2AQC283pqFdBAZhHD8


### Create a comment on post with pid 1 /posts
POST http://localhost:5000/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MDcwMjYyLCJleHAiOjE3NzUxNTY2NjJ9.XgwvWaEKEWx0JClHT6NSxqZGDxy73yF4HSQTbB4ldcE
Content-Type: application/json

{
  "title": "",
  "content": "Comment",
  "username": "sisyphus@gmail.com",
  "parent": 1,
  "tagString": ""
}

### Get comments on a post /posts/comments?pid=1 (protected)
GET http://localhost:5000/posts/comments?pid=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MDcwMjYyLCJleHAiOjE3NzUxNTY2NjJ9.XgwvWaEKEWx0JClHT6NSxqZGDxy73yF4HSQTbB4ldcE






### Send a notification POST /notifications/ (protected)
POST http://localhost:5000/notifications
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MDAzMjY3LCJleHAiOjE3NzUwODk2Njd9.FgMhTlvGHzVgahH2dWRwuW1ZwuerkjZvL2VL8FoaZJ0

{
  "user_id": "1",
  "post_id": "1",
  "content_post_id": "2",
  "message": "something"
}

### Fetch all notifs GET /notifications (protected)
GET http://localhost:5000/notifications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MDAzMjY3LCJleHAiOjE3NzUwODk2Njd9.FgMhTlvGHzVgahH2dWRwuW1ZwuerkjZvL2VL8FoaZJ0

### Update a notification PUT /notifications/:nid (protected)
PUT http://localhost:5000/notifications/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MDAzMjY3LCJleHAiOjE3NzUwODk2Njd9.FgMhTlvGHzVgahH2dWRwuW1ZwuerkjZvL2VL8FoaZJ0
