### GET / 
GET http://localhost:5000

### Register a user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "sisyphus@gmail.com",
  "password": "123123123"
}

### Register a user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "username1",
  "password": "123123123"
}

### Login a user POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "sisyphus@gmail.com",
  "password": "123123123"
}

### Login a user with wrong password POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "sisyphus@gmail.com",
  "password": "wrongpass"
}







### Fetch all posts GET /posts (protected)
GET http://localhost:5000/posts/all?pid=-1&sort=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MTY3MjM1LCJleHAiOjE3NzUyNTM2MzV9.L99WDuu13LHRFM00p7z_hSUsFZNiIDOJGNG0UXH5PPE

### Creates a new post POST /posts (protected)
POST http://localhost:5000/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MTY0NDY1LCJleHAiOjE3NzUyNTA4NjV9.tWDaw92sVvRfqn6lhZbR2Q3KM95xoaGYJT7edKMuhbQ
Content-Type: application/json

{
  "title": "title",
  "content": "this is the post content",
  "username": "sisyphus@gmail.com",
  "parent": null,
  "tagString": "Intro"
}

### Update a post PUT /posts/:id (protected)
PUT http://localhost:5000/posts/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MTY2ODMxLCJleHAiOjE3NzUyNTMyMzF9.w7T5fprLjksP7cwyZNnug-Q-QfYs40-0RD6udwxv8Ak

{
  "title": "new title",
  "content": "new content",
  "tagString": "Discussion"
}


### Delete a post DELETE /posts/:id (protected)
DELETE http://localhost:5000/posts/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MTY3MjM1LCJleHAiOjE3NzUyNTM2MzV9.L99WDuu13LHRFM00p7z_hSUsFZNiIDOJGNG0UXH5PPE


### Create a comment on post with pid 1 /posts
POST http://localhost:5000/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MDcwMjYyLCJleHAiOjE3NzUxNTY2NjJ9.XgwvWaEKEWx0JClHT6NSxqZGDxy73yF4HSQTbB4ldcE
Content-Type: application/json

{
  "title": "",
  "content": "Comment",
  "username": "sisyphus@gmail.com",
  "parent": 1,
  "tagString": ""
}

### Get comments on a post /posts/comments?pid=1 (protected)
GET http://localhost:5000/posts/comments?pid=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MDcwMjYyLCJleHAiOjE3NzUxNTY2NjJ9.XgwvWaEKEWx0JClHT6NSxqZGDxy73yF4HSQTbB4ldcE




### Get all tags GET /tags (protected)
GET http://localhost:5000/tags
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MTYzMDY0LCJleHAiOjE3NzUyNDk0NjR9.uDcKK7H9fBalCBnhg93do7ksx7JJ-8Fb6_T9Cd4EHQc

### Create a new tag POST /tags (protected)
POST http://localhost:5000/tags
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc1MTY0NjM1LCJleHAiOjE3NzUyNTEwMzV9.iw8Ch5fwyueV8W_rXi9OpbAIVWgdtMvX4avybhYavWU
Content-Type: application/json

{
  "tag": "newTag"
}

### Send a notification POST /notifications/ (protected)
POST http://localhost:5000/notifications
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MTYzNDM0LCJleHAiOjE3NzUyNDk4MzR9.3CRFbvmR081-xmDWMtaAzdJCM4TuBqyQyXlQtjZUbkI

{
  "user_id": "1",
  "post_id": "1",
  "content_post_id": "2",
  "message": "something"
}

### Fetch all notifs GET /notifications (protected)
GET http://localhost:5000/notifications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MTYzNDM0LCJleHAiOjE3NzUyNDk4MzR9.3CRFbvmR081-xmDWMtaAzdJCM4TuBqyQyXlQtjZUbkI

### Update a notification PUT /notifications/:nid (protected)
PUT http://localhost:5000/notifications/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1MTYzNDM0LCJleHAiOjE3NzUyNDk4MzR9.3CRFbvmR081-xmDWMtaAzdJCM4TuBqyQyXlQtjZUbkI
